Tweak configuration docs
mozilla/django-csp pull request #146
Opened 2020-03-03 14:01 UTC by jaap3

* Change formatting and some wording for readability sake
* Make defaults reflect the actual default values

2020-03-17 10:53 UTC, jaap3 commented
@EnTeQuAk could you please take a look at this? Thanks!

2021-07-26 18:40 UTC, g-k commented
This lgtm on first pass. @jaap3 can you rebase this PR? Thanks!

2021-07-27 11:11 UTC, jaap3 commented
@g-k I've rebased and fixed some minor spelling issues while I was at it, please take a look. Thanks!

2021-07-27 11:21 UTC, jaap3 commented on docs/configuration.rst
> +    Note: This doesn't use ``default-src`` as a fall-back.
This doesn't belong here, I'll remove it

2021-07-27 11:21 UTC, jaap3 commented on docs/configuration.rst
> +    Note: This doesn't use ``default-src`` as a fall-back.
This doesn't belong here, I'll remove it

2021-07-27 11:21 UTC, jaap3 commented on docs/configuration.rst
> +    Note: This doesn't use ``default-src`` as a fall-back.
This doesn't belong here, I'll remove it

2021-07-27 11:21 UTC, jaap3 commented on docs/configuration.rst
>      Valid values: ``'script'``
Let me change this to ` ``['script']`` `, as this setting requires a `tuple` or `list`

2021-07-27 11:21 UTC, jaap3 commented on docs/configuration.rst
> +    Note: This doesn't use ``default-src`` as a fall-back.
This seems like it doesn't belong here

2021-07-27 11:21 UTC, jaap3 commented on docs/configuration.rst
> +    Valid values: a list of allowed policy names that may include
Let me change this to ` ``list`` ` to put emphasis on the fact that a python list needs to be used here

2021-07-27 11:21 UTC, jaap3 commented on docs/configuration.rst
> +    Note: The nonce value will only be included if ``request.cps_nonce``
let me change included to generated, it is more correct that way

2021-07-27 11:21 UTC, jaap3 commented on docs/configuration.rst
> +    A ``tuple`` of URL prefixes. URLs beginning with any of these will
Add (not a ``list``) here to put emphasis on the fact that it may not be a list (in contrary to other settings)

2021-07-27 14:12 UTC, g-k requested changes
Thanks for rebasing! I took a more detailed look and have a couple nitpicks, but it looks good overall.

2021-07-27 14:12 UTC, g-k commented on docs/configuration.rst
> +.. _Content-Security-Policy: https://www.w3.org/TR/CSP/
👍

2021-07-27 14:12 UTC, g-k commented on docs/configuration.rst
> -    Note: This doesn't use default-src as a fall-back.
👍 this isn't a src list so we can remove this comment about the fallback

2021-07-27 14:12 UTC, g-k commented on docs/configuration.rst
> -    Note: This doesn't use default-src as a fall-back.
nit: we should keep this note.

2021-07-27 14:12 UTC, g-k commented on docs/configuration.rst
> +    Note: The nonce value will only be generated if ``request.cps_nonce``
nit: typo should be `request.csp_nonce`

2021-07-28 07:13 UTC, jaap3 commented on docs/configuration.rst
> +    Note: The nonce value will only be generated if ``request.cps_nonce``
good catch

2021-07-28 13:17 UTC, g-k approved these changes
lgtm thank you!

2021-07-28 13:17 UTC, merged