Add support for csp_clear decorator.
mozilla/django-csp pull request #202
Opened 2023-12-21 21:06 UTC by tim-schilling

This allows a directive to be cleared / unset entirely for a particular view.

Closes #201

2024-01-30 12:43 UTC, stevejalim requested changes
Thanks for this @tim-schilling -- in my capacity as not-the-official-maintainer-but-keen-to-help, I can see how this could be useful to others -- and certainly makes it easier to get out of a hole if, say, auth has to happen on a different domain compared to the iframed content.

I've suggested some minor docs tweaks, and then it'll need rebasing and conflicts fixing, I'm afraid.

I'm thinking that if a 3.8 release remains focused on Django+Python updates and generally bringing the project up to date, this changeset could be a good one for 3.9

2024-01-30 12:43 UTC, stevejalim commented on docs/decorators.rst
> +a directive will take priority over any of the other options.
I wonder if an admonition directive here like `warning` or even `danger` might be worthwhile.

2024-01-30 12:43 UTC, stevejalim commented on docs/decorators.rst
> +    # Will allow this particular view to be served in an iframe from any\
Suggestion: adding a splash of extra clarification

```suggestion
    # 
    # Using the @csp_clear decorator to clear the `frame-ancestors` directive 
    # for this particular view will allow it to be served in an iframe from _any_
```

2024-01-30 12:43 UTC, stevejalim commented on docs/decorators.rst
> +(They are also case-insensitive.)::
Suggestion: worth adding an explicit example of this

```suggestion
(They are also case-insensitive, so `img-src` also works)::
```

2024-06-06 22:38 UTC, robhudson commented
Since the underlying code changed drastically I'm going to close this. We're discussing the need for this in #201.

2024-06-06 22:38 UTC, closed without merging